'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.howItWorks': 'How it works',
    'nav.pricing': 'Pricing',
    'nav.testimonials': 'Testimonials',
    'nav.logIn': 'Log in',
    'nav.getAccess': 'Get Access Now',
    
    // Hero Section
    'hero.title': 'FREE Digital Menu That Boosts Sales',
    'hero.subtitle': 'Create your smart QR menu in 5 minutes. Start free, stay free. No setup fees, no credit card required.',
    'hero.placeholder': 'Enter your restaurant name...',
    'hero.button': 'Start Free Now',
    'hero.guarantee': '✓ FREE forever • ✓ 5-minute setup • ✓ Increase sales instantly',
    'hero.salesBoost': '+20%',
    'hero.salesBoostLabel': 'Sales boost',
    'hero.setupTime': '5 min',
    'hero.setupTimeLabel': 'Setup time',
    
    // Social Proof Section
    'socialProof.badge': 'Success Stories',
    'socialProof.testimonial': '"We set it up in 10 minutes. Our drink sales went up 20% in the first week!"',
    'socialProof.author': 'Café Owner, Early User',
    'socialProof.trustedByBadge': 'FREE for cafés, bars & restaurants worldwide',
    'socialProof.trustedBy': 'Trusted by cafés, bars & restaurants worldwide',
    
    // Value Props Section
    'valueProps.badge': '✨ Value Proposition',
    'valueProps.title': 'Why Choose Our Smart QR Menu?',
    'valueProps.subtitle': 'Everything you need to turn your menu into a powerful sales tool',
    'valueProps.feature1': '💡 Increase Revenue Instantly',
    'valueProps.feature1Desc': 'Recommend sides, drinks, and combos right inside your menu.',
    'valueProps.feature2': '⚡ 5-Minute Setup',
    'valueProps.feature2Desc': 'Build your menu, print your QR, and start selling — no training needed.',
    'valueProps.feature3': '💰 Low Cost, High Return',
    'valueProps.feature3Desc': 'One small subscription can add hundreds in extra monthly sales.',
    'valueProps.feature4': '🎨 Your Brand, Your Menu',
    'valueProps.feature4Desc': 'Upload your logo, pick your colors, and look professional.',
    'valueProps.feature5': '📊 Simple Insights',
    'valueProps.feature5Desc': 'See what customers click on most and update instantly.',
    
    // Features Section
    'features.title': 'Smart Upselling Features That Generate More Revenue',
    'features.subtitle': 'Transform your digital menu into a money-making machine with our intelligent upselling system.',
    'features.smartRecommendations': 'AI-Powered Smart Recommendations',
    'features.smartRecommendationsDesc': 'Machine learning algorithms analyze customer behavior to suggest dishes that increase order value by 35%',
    'features.promotionalDishes': 'Dynamic Promotional Dishes',
    'features.promotionalDishesDesc': 'Automatically highlight bestsellers and high-margin items to maximize revenue per customer',
    'features.upsellingEngine': 'Intelligent Upselling Engine',
    'features.upsellingEngineDesc': 'Smart prompts that suggest add-ons, drinks, and desserts at the perfect moment',
    'features.bundleDeals': 'Irresistible Bundle Deals',
    'features.bundleDealsDesc': 'Create combo offers that customers can\'t resist, increasing average order size by 40%',
    'features.noWebsiteTitle': 'No Money-Making Website? No Problem!',
    'features.noWebsiteDesc': 'We\'ll generate a fully functional restaurant website with online ordering that turns visitors into paying customers.',
    'features.website': 'Professional restaurant website',
    'features.ordering': 'Online ordering system',
    'features.mobile': 'Mobile-optimized design',
    'features.growth': '162% sales growth guaranteed',
    'features.preview': 'Live Preview: Your customers can browse your menu, place orders, and pay online - all from your professional website.',
    'features.yourWebsite': 'Your Restaurant Website',
    'features.completeOrdering': 'Complete with online ordering',
    'features.livePreview': 'Live Preview',
    
    // Benefits Section
    'benefits.title': 'Why 2,500+ Restaurants Choose OishiMenu',
    'benefits.subtitle': 'The easiest way to increase your restaurant\'s revenue with zero risk',
    'benefits.setup': '5-Minute Setup',
    'benefits.setupDesc': 'From signup to live menu in under 5 minutes. No technical skills required.',
    'benefits.setupHighlight': 'Fastest setup in the industry',
    'benefits.zeroCommissions': 'Zero Commissions',
    'benefits.zeroCommissionsDesc': 'Keep 100% of your revenue. No hidden fees, no monthly charges, no commissions.',
    'benefits.zeroCommissionsHighlight': 'Free forever',
    'benefits.revenueIncrease': '35% Revenue Increase',
    'benefits.revenueIncreaseDesc': 'Average restaurant sees 35% more revenue within 30 days of implementation.',
    'benefits.revenueIncreaseHighlight': 'Guaranteed results',
    'benefits.happyRestaurants': '2,500+ Happy Restaurants',
    'benefits.happyRestaurantsDesc': 'Join thousands of restaurants already using our system to increase their revenue.',
    'benefits.happyRestaurantsHighlight': 'Proven success',
    'benefits.aiUpselling': 'AI-Powered Upselling',
    'benefits.aiUpsellingDesc': 'Smart recommendations that automatically increase average order value by 40%.',
    'benefits.aiUpsellingHighlight': 'Works 24/7',
    'benefits.noRisk': 'No Risk, All Reward',
    'benefits.noRiskDesc': 'Free to use forever. No contracts, no commitments. Just results.',
    'benefits.noRiskHighlight': 'Risk-free',
    'benefits.readyTitle': 'Ready to Join the Success Stories?',
    'benefits.readyDesc': 'Start your 5-minute setup now and see your revenue increase within 30 days.',
    'benefits.averageRevenue': '35%',
    'benefits.averageRevenueDesc': 'Average revenue increase',
    
    // How It Works Section
    'howItWorks.badge': 'How It Works',
    'howItWorks.title': 'How to Boost Your Sales',
    'howItWorks.subtitle': 'Transform your menu into a powerful sales tool that increases revenue automatically.',
    'howItWorks.step1': 'Push Smart Options',
    'howItWorks.step1Desc': 'Automatically suggest add-ons, drinks, and upsells that customers actually want.',
    'howItWorks.step2': 'AI Recommendations',
    'howItWorks.step2Desc': 'Machine learning suggests the perfect items to boost every order value.',
    'howItWorks.step3': 'Easier Table Management',
    'howItWorks.step3Desc': 'Track orders, manage tables, and serve customers faster than ever before.',
    'howItWorks.ctaButton': 'Try It Free Now',
    'howItWorks.readyTitle': 'Ready to Start Making More Money?',
    'howItWorks.readyDesc': 'Join thousands of restaurants already using our system to increase their revenue.',
    'howItWorks.freeForever': 'Free forever',
    'howItWorks.fiveMinuteSetup': '5-minute setup',
    'howItWorks.noCoding': 'No coding required',
    
    // Testimonials Section
    'testimonials.title': 'Social Proof / Trust Builder',
    'testimonials.subtitle': 'Real results from real restaurants using our revenue-boosting system.',
    'testimonials.maria': '"We set it up in 10 minutes. Our drink sales went up 20% in the first week!" – Café Owner, Early User',
    'testimonials.james': '',
    'testimonials.sarah': '',
    
    // Pricing Section
    'pricing.badge': 'OishiMenu Pricing',
    'pricing.title': '14-Day Free Trial',
    'pricing.subtitle': 'Experience the Growth package with full features. After trial, account automatically switches to Starter (you can upgrade anytime).',
    'pricing.monthly': 'Monthly',
    'pricing.annually': 'Annually',
    'pricing.save2months': 'Save 2 months',
    'pricing.starterTitle': 'Starter',
    'pricing.starterPrice': 'Free',
    'pricing.starterPriceAnnual': 'Free',
    'pricing.starterPeriod': 'forever',
    'pricing.starterPeriodAnnual': 'forever',
    'pricing.starterButton': 'Get Starter',
    'pricing.starterDesc': 'Perfect for small cafes and restaurants looking to digitize their menu quickly and efficiently.',
    'pricing.starterFeature1': 'Free up to 1,500 orders/month (≈ 50 orders/day)',
    'pricing.starterFeature1Upgrade': '+$15/month to upgrade to 3,000 orders/month (≈ 100 orders/day)',
    'pricing.starterFeature2': 'Basic logo & color customization',
    'pricing.starterFeature3': 'Single QR code for menu',
    'pricing.starterFeature4': 'Create options & cross-sale suggestions',
    'pricing.starterFeature5': 'Basic dashboard (orders, scans)',
    'pricing.starterFeature6': 'Shows "Powered by OishiMenu" (+$15/month to remove)',
    'pricing.standardTitle': 'Standard',
    'pricing.standardPrice': '$59',
    'pricing.standardPriceAnnual': '$590',
    'pricing.standardPeriod': 'per month',
    'pricing.standardPeriodAnnual': 'per year',
    'pricing.standardButton': 'Get Standard',
    'pricing.standardDesc': 'Perfect for mid-sized restaurants wanting to optimize revenue and strengthen their brand.',
    'pricing.standardFeature1': 'Up to 6,000 orders/month (≈ 200 orders/day)',
    'pricing.standardFeature2': 'All Starter features',
    'pricing.standardFeature3': 'QR code for each table',
    'pricing.standardFeature4': 'Remove "Powered by OishiMenu" free',
    'pricing.standardFeature5': 'Advanced dashboard (bestsellers, cross-sale rates)',
    'pricing.standardFeature6': 'Priority email support',
    'pricing.growthTitle': 'Growth',
    'pricing.growthPrice': '$89',
    'pricing.growthPriceAnnual': '$890',
    'pricing.growthPeriod': 'per month',
    'pricing.growthPeriodAnnual': 'per year',
    'pricing.growthButton': 'Get Growth',
    'pricing.growthDesc': 'Perfect for restaurant chains and large establishments managing multiple locations.',
    'pricing.growthFeature1': 'Up to 30,000 orders/month (≈ 1,000 orders/day)',
    'pricing.growthFeature2': 'All Standard features',
    'pricing.growthFeature3': 'Manage multiple branches in one account',
    'pricing.growthFeature4': 'Consolidated branch reporting',
    'pricing.ctaText': 'Start 14-day free trial — no credit card required.',
    'pricing.placeholder': 'Enter your restaurant name...',
    'pricing.ctaButton': 'Start Free Trial',
    'pricing.guarantee': 'Cancel anytime • No contracts • Full features during trial',
    
    // CTA Section
    'cta.trustSignal': '🔒 Trusted by restaurants worldwide • 🚀 Start selling more today',
    'cta.title': 'Your menu can make more money starting tonight.',
    'cta.subtitle': 'Join 2,500+ restaurants already boosting their sales',
    'cta.placeholder': 'Enter your restaurant name...',
    'cta.button': '👉 Build My Free Menu',
    'cta.guarantee': 'Cancel anytime. Keep your menu forever, even on the free plan.',
    'cta.urgency': 'Limited time: Get premium features free for 30 days',
    'cta.stats1': '2,500+',
    'cta.stats1Label': 'Happy restaurants',
    'cta.stats2': '35%',
    'cta.stats2Label': 'Average revenue boost',
    'cta.stats3': '5 min',
    'cta.stats3Label': 'Setup time',
    'cta.benefit1': '⚡ Setup in 5 minutes',
    'cta.benefit2': '💰 Average 35% revenue increase',
    'cta.benefit3': '🔄 Cancel anytime, keep forever',
    'cta.benefit4': '🎯 No contracts, no commitments',
    
    // Dashboard Navigation
    'dashboard.nav.dashboard': 'Dashboard',
    'dashboard.nav.restaurants': 'Restaurants',
    'dashboard.nav.menuBuilder': 'Menu Builder',
    'dashboard.nav.pos': 'POS',
    'dashboard.nav.orders': 'Orders',
    'dashboard.nav.tables': 'Tables',
    'dashboard.nav.settings': 'Settings',
    'dashboard.nav.analytics': 'Analytics',
    'dashboard.nav.public': 'Public Menu',
    'dashboard.nav.restaurantOwner': 'Restaurant Owner',
    'dashboard.nav.signOut': 'Sign out',

    // Dashboard Content
    'dashboard.welcome': 'Welcome back!',
    'dashboard.description': "Here's what's happening with your restaurant.",
    'dashboard.analytics.revenue': 'Revenue',
    'dashboard.analytics.orders': 'Orders',
    'dashboard.analytics.averageOrder': 'Average Order',
    'dashboard.analytics.completionRate': 'Completion Rate',
    'dashboard.analytics.noData': 'No data available',
    'dashboard.analytics.startMessage': 'Start by adding some menu items and receiving orders.',
    'dashboard.stats.fromPreviousPeriod': 'from previous period',
    'dashboard.stats.vsLast': 'vs last',

    // Quick Actions
    'dashboard.quickActions.title': 'Quick Actions',
    'dashboard.quickActions.description': 'Common tasks to get you started',
    'dashboard.quickActions.addMenuItem': 'Add Menu Item',
    'dashboard.quickActions.openPOS': 'Open POS System',
    'dashboard.quickActions.posSystem': 'POS System',
    'dashboard.quickActions.previewPublicMenu': 'Preview Public Menu',
    'dashboard.quickActions.previewMenu': 'Preview Menu',
    'dashboard.quickActions.viewAnalytics': 'View Analytics',
    'dashboard.quickActions.manageOrders': 'Manage Orders',

    // Hourly Activity
    'dashboard.hourlyActivity.title': 'Hourly Activity',
    'dashboard.hourlyActivity.description': 'Orders by hour of day',

    // Top Menu Items
    'dashboard.topMenuItems.title': 'Top Menu Items',
    'dashboard.topMenuItems.description': 'Most popular items by orders',
    'dashboard.topMenuItems.orders': 'orders',

    // Revenue by Dates
    'dashboard.revenueByDates.title': 'Revenue by Date',
    'dashboard.revenueByDates.description': 'Daily revenue for the last 7 days',
    'dashboard.revenueByDates.avgPerDay': 'Avg per day',
    'dashboard.revenueByDates.revenue': 'Revenue',
    'dashboard.revenueByDates.orders': 'Orders',
    'dashboard.revenueByDates.thisWeek': 'This Week',
    'dashboard.revenueByDates.bestDay': 'Best Day',
    'dashboard.revenueByDates.totalOrders': 'Total Orders',

    // Dashboard Header Actions
    'dashboard.timeRange.today': 'Today',
    'dashboard.timeRange.yesterday': 'Yesterday',
    'dashboard.timeRange.thisWeek': 'This Week',
    'dashboard.timeRange.lastWeek': 'Last Week',
    'dashboard.timeRange.thisMonth': 'This Month',
    'dashboard.timeRange.lastMonth': 'Last Month',
    'dashboard.actions.customRange': 'Custom Range',
    'dashboard.actions.custom': 'Custom',
    'dashboard.actions.exportReport': 'Export Report',
    'dashboard.actions.export': 'Export',

    // Restaurants Page
    'dashboard.restaurants.loading': 'Loading restaurants...',
    'dashboard.restaurants.createTitle': 'Create Your Restaurant',
    'dashboard.restaurants.managementTitle': 'Restaurant Management',
    'dashboard.restaurants.createDescription': 'Complete your setup by creating your restaurant profile',
    'dashboard.restaurants.managementDescription': 'Manage multiple restaurant locations, each with their own menu, tables, and data.',
    'dashboard.restaurants.welcomeTitle': "Welcome! Let's create your restaurant",
    'dashboard.restaurants.welcomeDescription': "We'll help you set up your restaurant profile and then choose a menu template to get started quickly.",
    'dashboard.restaurants.form.name': 'Restaurant Name',
    'dashboard.restaurants.form.namePlaceholder': 'Your restaurant name',
    'dashboard.restaurants.form.description': 'Description',
    'dashboard.restaurants.form.descriptionPlaceholder': 'Brief description of your restaurant',
    'dashboard.restaurants.form.address': 'Address',
    'dashboard.restaurants.form.addressPlaceholder': '123 Main St, City, State',
    'dashboard.restaurants.form.phone': 'Phone',
    'dashboard.restaurants.form.phonePlaceholder': '(555) 123-4567',
    'dashboard.restaurants.form.email': 'Email',
    'dashboard.restaurants.form.emailPlaceholder': 'contact@restaurant.com',
    'dashboard.restaurants.form.creating': 'Creating...',
    'dashboard.restaurants.form.createButton': 'Create Restaurant & Continue',
    'dashboard.restaurants.noRestaurantsTitle': 'No Restaurants Yet',
    'dashboard.restaurants.noRestaurantsDescription': 'Create your first restaurant location to start managing menus, tables, and orders.',
    'dashboard.restaurants.yourRestaurants': 'Your Restaurants',
    'dashboard.restaurants.selectDescription': 'Select a restaurant to manage its data',
    'dashboard.restaurants.restaurantSingular': 'restaurant',
    'dashboard.restaurants.restaurantsPlural': 'restaurants',

    // Menu Builder
    'menuBuilder.header.title': 'Menu Builder',
    'menuBuilder.header.description': 'Create and manage your restaurant menu with drag-and-drop ease.',
    'menuBuilder.header.previewPublicMenu': 'Preview Public Menu',
    'menuBuilder.header.previewMenu': 'Preview Menu',
    'menuBuilder.header.livePreviewReady': 'Live Preview Ready',
    'menuBuilder.header.quickTemplates': 'Quick Templates',
    'menuBuilder.header.templates': 'Templates',
    'menuBuilder.header.restaurantMenu': 'Restaurant Menu',
    'menuBuilder.header.general': 'General',
    'menuBuilder.header.cafeMenu': 'Cafe Menu',
    'menuBuilder.header.coffeePastries': 'Coffee & Pastries',
    'menuBuilder.header.pizzaShop': 'Pizza Shop',
    'menuBuilder.header.pizzaSides': 'Pizza & Sides',
    'menuBuilder.header.clearMenu': 'Clear Menu',
    'menuBuilder.header.clear': 'Clear',
    'menuBuilder.header.scanToView': 'Scan to View Menu',
    'menuBuilder.header.qrDescription': 'Customers can scan this QR code to instantly access your menu',
    'menuBuilder.header.copyUrl': 'Copy URL',
    'menuBuilder.header.downloadQr': 'Download QR',
    'menuBuilder.header.urlCopied': 'Menu URL copied to clipboard!',
    'menuBuilder.header.menuUrl': 'Menu URL',
    'menuBuilder.tabs.builder': 'Builder',
    'menuBuilder.tabs.options': 'Options',
    'menuBuilder.tabs.brand': 'Brand',

    // Menu Builder - Builder Tab
    'menuBuilder.builder.categoryNamePlaceholder': 'Category name',
    'menuBuilder.builder.add': 'Add',
    'menuBuilder.builder.cancel': 'Cancel',
    'menuBuilder.builder.addCategory': 'Add Category',
    'menuBuilder.builder.collapseAll': 'Collapse All',
    'menuBuilder.builder.collapse': 'Collapse',
    'menuBuilder.builder.expandAll': 'Expand All',
    'menuBuilder.builder.expand': 'Expand',
    'menuBuilder.builder.noCategoriesTitle': 'No categories yet',
    'menuBuilder.builder.noCategoriesDescription': 'Start by adding your first category to organize your menu items',
    'menuBuilder.builder.addFirstCategory': 'Add Your First Category',
    'menuBuilder.builder.menuItem': 'Menu Item',

    // Menu Builder - Options Tab
    'menuBuilder.options.title': 'Menu Options',
    'menuBuilder.options.description': 'Manage sizes, toppings, and other options for your menu items',
    'menuBuilder.options.addOptionGroup': 'Add Option Group',
    'menuBuilder.options.addGroup': 'Add Group',
    'menuBuilder.options.editOptionGroup': 'Edit Option Group',
    'menuBuilder.options.createOptionGroup': 'Create Option Group',
    'menuBuilder.options.editDescription': 'Update the option group settings and linked dishes',
    'menuBuilder.options.createDescription': 'Create a new option group (e.g., Size, Toppings, Extras)',
    'menuBuilder.options.groupName': 'Group Name',
    'menuBuilder.options.groupNamePlaceholder': 'e.g., Size, Toppings, Extras',
    'menuBuilder.options.descriptionOptional': 'Description (Optional)',
    'menuBuilder.options.descriptionPlaceholder': 'Describe this option group...',
    'menuBuilder.options.selectionType': 'Selection Type',
    'menuBuilder.options.singleChoice': 'Single Choice (Radio)',
    'menuBuilder.options.multipleChoice': 'Multiple Choice (Checkboxes)',
    'menuBuilder.options.required': 'Required',
    'menuBuilder.options.minSelections': 'Min Selections',
    'menuBuilder.options.maxSelections': 'Max Selections',
    'menuBuilder.options.applyToDishes': 'Apply to Dishes',
    'menuBuilder.options.selectDishesDescription': 'Select which dishes this option group will be available for',
    'menuBuilder.options.availableForDishes': 'Will be available for {count} dish(es)',
    'menuBuilder.options.cancel': 'Cancel',
    'menuBuilder.options.updateGroup': 'Update Group',
    'menuBuilder.options.createGroup': 'Create Group',
    'menuBuilder.options.addOption': 'Add Option',
    'menuBuilder.options.addOptionToGroup': 'Add a new option to "{groupName}"',
    'menuBuilder.options.optionName': 'Option Name',
    'menuBuilder.options.optionNamePlaceholder': 'e.g., Large, Extra Cheese, No Onions',
    'menuBuilder.options.additionalPrice': 'Additional Price',
    'menuBuilder.options.defaultOption': 'Default Option',

    // Menu Builder - Brand Tab
    'menuBuilder.brand.menuPreview': 'Menu Preview',
    'menuBuilder.brand.menuPreviewDescription': 'See how your menu looks to customers',
    'menuBuilder.brand.previewDevice': 'Preview Device',
    'menuBuilder.brand.mobile': 'Mobile',
    'menuBuilder.brand.tablet': 'Tablet',
    'menuBuilder.brand.desktop': 'Desktop',
    'menuBuilder.brand.themeColor': 'Theme Color',
    'menuBuilder.brand.restaurantLogo': 'Restaurant Logo',
    'menuBuilder.brand.restaurantLogoAlt': 'Restaurant Logo',
    'menuBuilder.brand.replaceLogo': 'Replace Logo',
    'menuBuilder.brand.uploadLogo': 'Upload Logo',
    'menuBuilder.brand.logoFileTypes': 'PNG or JPG, max 2MB',
    'menuBuilder.brand.autoSave': 'Auto-save',
    'menuBuilder.brand.autoSaveDescription': 'Automatically save changes every 2 seconds',
    'menuBuilder.brand.makeMenuPublic': 'Make Menu Public',
    'menuBuilder.brand.makeMenuPublicDescription': 'Allow customers to view your menu',
    'menuBuilder.brand.showPoweredBy': 'Show "Powered by OishiMenu"',
    'menuBuilder.brand.showPoweredByDescription': 'Display our branding in menu footer',
    'menuBuilder.brand.customize': 'Customize',
    'menuBuilder.brand.share': 'Share',
    'menuBuilder.brand.livePreview': 'Live Preview',
    'menuBuilder.brand.menuIsLive': 'Your menu is live and accessible to customers',
    'menuBuilder.brand.menuIsPrivate': 'Your menu is private',
    'menuBuilder.brand.featured': 'Featured',
    'menuBuilder.brand.unavailable': 'Unavailable',
    'menuBuilder.brand.contains': 'Contains',
    'menuBuilder.brand.menuFooterText': 'Scan QR code to order • Table service available',

    // POS System
    'pos.title': 'Point of Sale',
    'pos.description': 'Create orders manually for walk-in customers or phone orders',
    'pos.accountDisabled': 'Account Disabled',
    'pos.accountDisabledMessage': 'Your account has been disabled. You cannot create orders. Please contact support for assistance.',
    'pos.loadingPOS': 'Loading POS system...',
    'pos.menuItems': 'Menu Items',
    'pos.menuItemsDescription': 'Click to add items to the order',
    'pos.noMenuItemsTitle': 'No Menu Items Available',
    'pos.noMenuItemsDescription': 'Create your menu in the Menu Builder to start taking orders.',
    'pos.goToMenuBuilder': 'Go to Menu Builder',
    'pos.orderCart': 'Order Cart',
    'pos.items': 'items',
    'pos.reviewOrder': 'Review and complete the order',
    'pos.tableSelection': 'Table Selection',
    'pos.selectTable': 'Select table',
    'pos.table': 'Table',
    'pos.walkIn': 'Walk-in',
    'pos.customerName': 'Customer Name',
    'pos.enterCustomerName': 'Enter customer name',
    'pos.noItemsInCart': 'No items in cart',
    'pos.paymentMethod': 'Payment Method',
    'pos.cash': 'Cash',
    'pos.card': 'Card',
    'pos.digitalWallet': 'Digital Wallet',
    'pos.subtotal': 'Subtotal',
    'pos.tax': 'Tax (8%)',
    'pos.total': 'Total',
    'pos.creatingOrder': 'Creating Order...',
    'pos.orderCompleted': 'Order Completed',
    'pos.createOrder': 'Create Order',
    'pos.printReceipt': 'Print Receipt',
    'pos.newOrder': 'New Order',
    'pos.orderCreatedSuccessfully': 'Order created successfully!',
    'pos.walkInCustomer': 'Walk-in Customer',
    'pos.orderCreationFailed': 'Failed to create order. Please try again.',

    // Orders
    'orders.title': 'Orders',
    'orders.description': 'Manage and track customer orders in real-time.',
    'orders.activeOrders': 'Active Orders',
    'orders.active': 'Active',
    'orders.allOrders': 'All Orders',
    'orders.all': 'All',
    'orders.loadingActiveOrders': 'Loading active orders...',
    'orders.kitchenDashboard': 'Kitchen Dashboard',
    'orders.kitchenDashboardDescription': 'Active orders requiring attention',
    'orders.priority.high': 'High Priority',
    'orders.priority.highShort': 'High',
    'orders.priority.medium': 'Medium Priority',
    'orders.priority.mediumShort': 'Med',
    'orders.priority.low': 'Low Priority',
    'orders.priority.lowShort': 'Low',
    'orders.searchPlaceholder': 'Search by table, customer, or order ID...',
    'orders.filterByStatus': 'Filter by status',
    'orders.filter.allActive': 'All Active',
    'orders.noActiveOrders': 'No active orders',
    'orders.allCaughtUp': 'All caught up! New orders will appear here.',
    'orders.status.pending': 'Pending',
    'orders.status.preparing': 'Preparing',
    'orders.status.ready': 'Ready',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'orders.time.justNow': 'Just now',
    'orders.time.minutesAgo': '{minutes}m ago',
    'orders.time.hoursAgo': '{hours}h ago',
    'orders.time.daysAgo': '{days}d ago',

    // Tables
    'tables.title': 'Tables',
    'tables.description': 'Manage restaurant seating areas and table layout.',
    'tables.addArea': 'Add Area',
    'tables.areaNamePlaceholder': 'Area name (e.g., Main Dining, Patio, Bar)',
    'tables.noAreasYet': 'No areas yet',
    'tables.addFirstAreaDescription': 'Start by adding your first dining area to organize your restaurant tables',
    'tables.expandAll': 'Expand All',
    'tables.expand': 'Expand',
    'tables.collapseAll': 'Collapse All',
    'tables.collapse': 'Collapse',
    'tables.tables': 'tables',
    'tables.orders': 'orders',
    'tables.status.active': 'Active',
    'tables.status.closed': 'Closed',
    'tables.status.maintenance': 'Maintenance',
    'tables.tableNamePlaceholder': 'Table name',
    'tables.addTable': 'Add Table',
    'tables.add': 'Add',
    'tables.noTablesInArea': 'No tables in this area yet',
    'tables.addFirstTable': 'Add First Table',
    'tables.dropTablesHere': 'Or drop tables here to move them to {areaName}',
    'tables.tableNameExists': 'A table named "{tableName}" already exists in {areaName}. Please choose a different name.',

    // Common
    'common.cancel': 'Cancel',

    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Manage your restaurant settings, profile, and preferences.',
    'settings.tabs.profile': 'Profile',
    'settings.tabs.subscription': 'Subscription',
    'settings.tabs.plan': 'Plan',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.notify': 'Notify',
    'settings.tabs.security': 'Security',
    'settings.profile.title': 'Profile Information',
    'settings.profile.description': 'Update your personal information and contact details.',
    'settings.profile.changePhoto': 'Change Photo',
    'settings.profile.change': 'Change',
    'settings.profile.photoFormat': 'JPG, PNG up to 2MB',
    'settings.profile.firstName': 'First Name',
    'settings.profile.lastName': 'Last Name',
    'settings.profile.email': 'Email',
    'settings.profile.phone': 'Phone',
    'settings.profile.saveChanges': 'Save Changes',
    'settings.profile.save': 'Save',

    // Insights
    'dashboard.insights.welcome': '📊 Welcome to your restaurant dashboard!',
    'dashboard.insights.addMenu': '🍽️ Add menu items to start receiving orders',
    'dashboard.insights.shareQR': '📱 Share your QR code with customers',

    // Footer
    'footer.copyright': '© 2024 OishiMenu. All rights reserved.'
  },
  vi: {
    // Navigation
    'nav.features': 'Tính năng',
    'nav.howItWorks': 'Cách hoạt động',
    'nav.pricing': 'Giá cả',
    'nav.testimonials': 'Đánh giá',
    'nav.logIn': 'Đăng nhập',
    'nav.getAccess': 'Truy cập ngay',
    
    // Hero Section
    'hero.title': 'Thực Đơn Số MIỄN PHÍ Tăng Doanh Số',
    'hero.subtitle': 'Tạo thực đơn QR thông minh trong 5 phút. Bắt đầu miễn phí, sử dụng miễn phí mãi mãi. Không phí thiết lập, không cần thẻ tín dụng.',
    'hero.placeholder': 'Nhập tên nhà hàng của bạn...',
    'hero.button': 'Bắt Đầu Miễn Phí',
    'hero.guarantee': '✓ MIỄN PHÍ mãi mãi • ✓ Thiết lập 5 phút • ✓ Tăng doanh số ngay lập tức',
    'hero.salesBoost': '+20%',
    'hero.salesBoostLabel': 'Tăng doanh số',
    'hero.setupTime': '5 phút',
    'hero.setupTimeLabel': 'Thời gian thiết lập',

    // Value Props Section
    'valueProps.badge': '✨ Đề Xuất Giá Trị',
    'valueProps.title': 'Tại Sao Chọn Thực Đơn QR Thông Minh Của Chúng Tôi?',
    'valueProps.subtitle': 'Mọi thứ bạn cần để biến thực đơn thành công cụ bán hàng mạnh mẽ',
    'valueProps.feature1': '💡 Tăng Doanh Thu Tức Thì',
    'valueProps.feature1Desc': 'Gợi ý món phụ, đồ uống và combo ngay trong thực đơn.',
    'valueProps.feature2': '⚡ Thiết Lập 5 Phút',
    'valueProps.feature2Desc': 'Tạo thực đơn, in QR và bắt đầu bán hàng — không cần đào tạo.',
    'valueProps.feature3': '💰 Chi Phí Thấp, Lợi Nhuận Cao',
    'valueProps.feature3Desc': 'Một gói đăng ký nhỏ có thể tăng thêm hàng trăm đô la doanh thu mỗi tháng.',
    'valueProps.feature4': '🎨 Thương Hiệu Của Bạn, Thực Đơn Của Bạn',
    'valueProps.feature4Desc': 'Tải lên logo, chọn màu sắc và trông chuyên nghiệp.',
    'valueProps.feature5': '📊 Thông Tin Chi Tiết Đơn Giản',
    'valueProps.feature5Desc': 'Xem khách hàng nhấp vào gì nhiều nhất và cập nhật ngay lập tức.',

    // Features Section
    'features.title': 'Tính Năng Bán Chéo Thông Minh Tạo Thêm Doanh Thu',
    'features.subtitle': 'Biến thực đơn kỹ thuật số thành cỗ máy kiếm tiền với hệ thống bán chéo thông minh.',
    'features.smartRecommendations': 'Gợi Ý Thông Minh AI',
    'features.smartRecommendationsDesc': 'Thuật toán học máy phân tích hành vi khách hàng để gợi ý món ăn tăng giá trị đơn hàng lên 35%',
    'features.promotionalDishes': 'Món Khuyến Mãi Động',
    'features.promotionalDishesDesc': 'Tự động làm nổi bật món bán chạy và món có lợi nhuận cao để tối đa hóa doanh thu mỗi khách hàng',
    'features.upsellingEngine': 'Công Cụ Bán Chéo Thông Minh',
    'features.upsellingEngineDesc': 'Gợi ý thông minh về món thêm, đồ uống và tráng miệng vào thời điểm hoàn hảo',
    'features.bundleDeals': 'Combo Không Thể Cưỡng Lại',
    'features.bundleDealsDesc': 'Tạo combo hấp dẫn mà khách hàng không thể từ chối, tăng kích thước đơn hàng trung bình lên 40%',
    'features.noWebsiteTitle': 'Không Có Website Kiếm Tiền? Không Vấn Đề!',
    'features.noWebsiteDesc': 'Chúng tôi sẽ tạo website nhà hàng chuyên nghiệp với đặt hàng trực tuyến biến khách truy cập thành khách hàng trả tiền.',
    'features.website': 'Website nhà hàng chuyên nghiệp',
    'features.ordering': 'Hệ thống đặt hàng trực tuyến',
    'features.mobile': 'Thiết kế tối ưu di động',
    'features.growth': 'Đảm bảo tăng trưởng 162%',
    'features.preview': 'Xem trước trực tiếp: Khách hàng có thể duyệt thực đơn, đặt hàng và thanh toán trực tuyến - tất cả từ website chuyên nghiệp của bạn.',
    'features.yourWebsite': 'Website Nhà Hàng Của Bạn',
    'features.completeOrdering': 'Hoàn chỉnh với đặt hàng trực tuyến',
    'features.livePreview': 'Xem Trước Trực Tiếp',

    // Benefits Section
    'benefits.title': 'Tại Sao 2,500+ Nhà Hàng Chọn OishiMenu',
    'benefits.subtitle': 'Cách dễ nhất để tăng doanh thu nhà hàng với rủi ro bằng không',
    'benefits.setup': 'Thiết Lập 5 Phút',
    'benefits.setupDesc': 'Từ đăng ký đến thực đơn hoạt động trong vòng 5 phút. Không cần kỹ năng kỹ thuật.',
    'benefits.setupHighlight': 'Thiết lập nhanh nhất ngành',
    'benefits.zeroCommissions': 'Không Hoa Hồng',
    'benefits.zeroCommissionsDesc': 'Giữ 100% doanh thu. Không phí ẩn, không phí hàng tháng, không hoa hồng.',
    'benefits.zeroCommissionsHighlight': 'Miễn phí mãi mãi',
    'benefits.revenueIncrease': 'Tăng 35% Doanh Thu',
    'benefits.revenueIncreaseDesc': 'Nhà hàng trung bình thấy tăng 35% doanh thu trong 30 ngày triển khai.',
    'benefits.revenueIncreaseHighlight': 'Kết quả đảm bảo',
    'benefits.happyRestaurants': '2,500+ Nhà Hàng Hài Lòng',
    'benefits.happyRestaurantsDesc': 'Tham gia hàng nghìn nhà hàng đã sử dụng hệ thống của chúng tôi để tăng doanh thu.',
    'benefits.happyRestaurantsHighlight': 'Thành công đã chứng minh',
    'benefits.aiUpselling': 'Bán Chéo AI',
    'benefits.aiUpsellingDesc': 'Gợi ý thông minh tự động tăng giá trị đơn hàng trung bình lên 40%.',
    'benefits.aiUpsellingHighlight': 'Hoạt động 24/7',
    'benefits.noRisk': 'Không Rủi Ro, Chỉ Thưởng',
    'benefits.noRiskDesc': 'Sử dụng miễn phí mãi mãi. Không hợp đồng, không cam kết. Chỉ kết quả.',
    'benefits.noRiskHighlight': 'Không rủi ro',
    'benefits.readyTitle': 'Sẵn Sàng Tham Gia Câu Chuyện Thành Công?',
    'benefits.readyDesc': 'Bắt đầu thiết lập 5 phút ngay bây giờ và thấy doanh thu tăng trong 30 ngày.',
    'benefits.averageRevenue': '35%',
    'benefits.averageRevenueDesc': 'Tăng doanh thu trung bình',
    
    // Social Proof Section
    'socialProof.badge': 'Câu Chuyện Thành Công',
    'socialProof.testimonial': '"Chúng tôi thiết lập trong 10 phút. Doanh số đồ uống tăng 20% trong tuần đầu tiên!"',
    'socialProof.author': 'Chủ Quán Cà Phê, Người Dùng Sớm',
    'socialProof.trustedBy': 'Được tin tưởng bởi các quán cà phê, quán bar & nhà hàng trên toàn thế giới',
    'socialProof.trustedByBadge': 'MIỄN PHÍ cho quán cà phê, quán bar & nhà hàng trên toàn thế giới',

    // How It Works Section
    'howItWorks.badge': 'Cách Hoạt Động',
    'howItWorks.title': 'Cách Tăng Doanh Số Của Bạn',
    'howItWorks.subtitle': 'Biến thực đơn thành công cụ bán hàng mạnh mẽ tự động tăng doanh thu.',
    'howItWorks.step1': 'Đẩy Tùy Chọn Thông Minh',
    'howItWorks.step1Desc': 'Tự động gợi ý món thêm, đồ uống và nâng cấp mà khách hàng thực sự muốn.',
    'howItWorks.step2': 'Gợi Ý AI',
    'howItWorks.step2Desc': 'Học máy gợi ý những món hoàn hảo để tăng giá trị mỗi đơn hàng.',
    'howItWorks.step3': 'Quản Lý Bàn Dễ Dàng Hơn',
    'howItWorks.step3Desc': 'Theo dõi đơn hàng, quản lý bàn và phục vụ khách hàng nhanh hơn bao giờ hết.',
    'howItWorks.ctaButton': 'Dùng Thử Miễn Phí Ngay',
    'howItWorks.readyTitle': 'Sẵn Sàng Bắt Đầu Kiếm Thêm Tiền?',
    'howItWorks.readyDesc': 'Tham gia hàng nghìn nhà hàng đã sử dụng hệ thống của chúng tôi để tăng doanh thu.',
    'howItWorks.freeForever': 'Miễn phí mãi mãi',
    'howItWorks.fiveMinuteSetup': 'Thiết lập 5 phút',
    'howItWorks.noCoding': 'Không cần lập trình',
    
    // Testimonials Section
    'testimonials.title': 'Chủ Nhà Hàng Nói Gì',
    'testimonials.subtitle': 'Kết quả thực từ các nhà hàng thực sử dụng hệ thống tăng doanh thu của chúng tôi.',
    'testimonials.maria': 'OishiMenu tăng đơn hàng trực tuyến của chúng tôi 162% chỉ trong 3 tháng. Chúng tôi từ $3,000 lên $7,800 doanh thu hàng tháng. Bán chéo AI như có chuyên gia bán hàng ở mỗi bàn!',
    'testimonials.james': 'Chúng tôi từ $2,000 lên $5,200 doanh thu hàng tháng. Gợi ý thông minh tăng đơn hàng trung bình lên 40%. Thiết lập chỉ mất 5 phút!',
    'testimonials.sarah': 'Khách hàng yêu thích trải nghiệm thực đơn kỹ thuật số. Đơn hàng tăng 35% và chúng tôi kiếm nhiều tiền hơn bao giờ hết! Tính năng combo đơn thuần tăng doanh thu $1,200/tháng.',
    
    // Pricing Section
    'pricing.badge': 'Bảng Giá OishiMenu',
    'pricing.title': 'Dùng thử miễn phí 14 ngày',
    'pricing.subtitle': 'Trải nghiệm Growth với đầy đủ tính năng. Sau thời gian dùng thử, tài khoản sẽ tự động chuyển về Starter (bạn có thể nâng cấp bất kỳ lúc nào).',
    'pricing.monthly': 'Hàng tháng',
    'pricing.annually': 'Hàng năm',
    'pricing.save2months': 'Tiết kiệm 2 tháng',
    'pricing.starterTitle': 'Starter',
    'pricing.starterPrice': 'Miễn phí',
    'pricing.starterPriceAnnual': 'Miễn phí',
    'pricing.starterPeriod': 'mãi mãi',
    'pricing.starterPeriodAnnual': 'mãi mãi',
    'pricing.starterButton': 'Chọn Starter',
    'pricing.starterDesc': 'Hoàn hảo cho quán cà phê và nhà hàng nhỏ muốn số hóa thực đơn nhanh chóng và hiệu quả.',
    'pricing.starterFeature1': 'Miễn phí tới 1.500 đơn/tháng (≈ 50 đơn/ngày)',
    'pricing.starterFeature1Upgrade': '+49.000 VND/tháng để nâng cấp tới 3.000 đơn/tháng (≈ 100 đơn/ngày)',
    'pricing.starterFeature2': 'Tùy chỉnh logo & màu sắc cơ bản',
    'pricing.starterFeature3': 'QR code đơn cho thực đơn',
    'pricing.starterFeature4': 'Tạo tùy chọn món và gợi ý bán kèm',
    'pricing.starterFeature5': 'Dashboard cơ bản (đơn hàng, lượt quét)',
    'pricing.starterFeature6': 'Hiển thị "Powered by OishiMenu" (+49.000 VND/tháng để xóa)',
    'pricing.standardTitle': 'Standard',
    'pricing.standardPrice': '199.000 VND',
    'pricing.standardPriceAnnual': '1.990.000 VND',
    'pricing.standardPeriod': 'mỗi tháng',
    'pricing.standardPeriodAnnual': 'mỗi năm',
    'pricing.standardButton': 'Chọn Standard',
    'pricing.standardDesc': 'Hoàn hảo cho nhà hàng cỡ vừa muốn tối ưu doanh thu và tăng cường thương hiệu.',
    'pricing.standardFeature1': 'Tối đa 6.000 đơn/tháng (≈ 200 đơn/ngày)',
    'pricing.standardFeature2': 'Tất cả tính năng của Starter',
    'pricing.standardFeature3': 'QR code riêng cho từng bàn',
    'pricing.standardFeature4': 'Xóa "Powered by OishiMenu" miễn phí',
    'pricing.standardFeature5': 'Dashboard nâng cao (món bán chạy, tỉ lệ click)',
    'pricing.standardFeature6': 'Hỗ trợ ưu tiên qua email',
    'pricing.growthTitle': 'Growth',
    'pricing.growthPrice': '299.000 VND',
    'pricing.growthPriceAnnual': '2.990.000 VND',
    'pricing.growthPeriod': 'mỗi tháng',
    'pricing.growthPeriodAnnual': 'mỗi năm',
    'pricing.growthButton': 'Chọn Growth',
    'pricing.growthDesc': 'Hoàn hảo cho chuỗi nhà hàng và cơ sở lớn quản lý nhiều địa điểm khác nhau.',
    'pricing.growthFeature1': 'Tối đa 30.000 đơn/tháng (≈ 1.000 đơn/ngày)',
    'pricing.growthFeature2': 'Tất cả tính năng của Standard',
    'pricing.growthFeature3': 'Quản lý nhiều chi nhánh trong cùng tài khoản',
    'pricing.growthFeature4': 'Báo cáo chi nhánh tổng hợp',
    'pricing.ctaText': 'Dùng thử miễn phí 14 ngày — không cần thẻ tín dụng.',
    'pricing.placeholder': 'Nhập tên nhà hàng của bạn...',
    'pricing.ctaButton': 'Bắt Đầu Dùng Thử',
    'pricing.guarantee': 'Hủy bất cứ lúc nào • Không hợp đồng • Đầy đủ tính năng khi dùng thử',

    // CTA Section
    'cta.trustSignal': '🔒 Được tin tưởng bởi nhà hàng trên toàn thế giới • 🚀 Bắt đầu bán nhiều hơn hôm nay',
    'cta.title': 'Thực đơn của bạn có thể kiếm được nhiều tiền hơn từ tối nay.',
    'cta.subtitle': 'Tham gia 2,500+ nhà hàng đã tăng doanh số',
    'cta.placeholder': 'Nhập tên nhà hàng của bạn...',
    'cta.button': '👉 Tạo Thực Đơn Miễn Phí',
    'cta.guarantee': 'Hủy bất cứ lúc nào. Giữ thực đơn mãi mãi, ngay cả với gói miễn phí.',
    'cta.urgency': 'Có thời hạn: Nhận tính năng premium miễn phí 30 ngày',
    'cta.stats1': '2,500+',
    'cta.stats1Label': 'Nhà hàng hài lòng',
    'cta.stats2': '35%',
    'cta.stats2Label': 'Tăng doanh thu trung bình',
    'cta.stats3': '5 phút',
    'cta.stats3Label': 'Thời gian thiết lập',
    'cta.benefit1': '⚡ Thiết lập trong 5 phút',
    'cta.benefit2': '💰 Trung bình tăng 35% doanh thu',
    'cta.benefit3': '🔄 Hủy bất cứ lúc nào, giữ mãi mãi',
    'cta.benefit4': '🎯 Không hợp đồng, không cam kết',
    
    // Dashboard Navigation
    'dashboard.nav.dashboard': 'Bảng điều khiển',
    'dashboard.nav.restaurants': 'Nhà hàng',
    'dashboard.nav.menuBuilder': 'Tạo thực đơn',
    'dashboard.nav.pos': 'POS',
    'dashboard.nav.orders': 'Đơn hàng',
    'dashboard.nav.tables': 'Bàn ăn',
    'dashboard.nav.settings': 'Cài đặt',
    'dashboard.nav.analytics': 'Phân tích',
    'dashboard.nav.public': 'Thực đơn công khai',
    'dashboard.nav.restaurantOwner': 'Chủ nhà hàng',
    'dashboard.nav.signOut': 'Đăng xuất',

    // Dashboard Content
    'dashboard.welcome': 'Chào mừng trở lại!',
    'dashboard.description': 'Đây là những gì đang diễn ra với nhà hàng của bạn.',
    'dashboard.analytics.revenue': 'Doanh thu',
    'dashboard.analytics.orders': 'Đơn hàng',
    'dashboard.analytics.averageOrder': 'Đơn hàng trung bình',
    'dashboard.analytics.completionRate': 'Tỷ lệ hoàn thành',
    'dashboard.analytics.noData': 'Không có dữ liệu',
    'dashboard.analytics.startMessage': 'Bắt đầu bằng cách thêm món ăn và nhận đơn hàng.',
    'dashboard.stats.fromPreviousPeriod': 'so với kỳ trước',
    'dashboard.stats.vsLast': 'so với kỳ trước',

    // Quick Actions
    'dashboard.quickActions.title': 'Thao tác nhanh',
    'dashboard.quickActions.description': 'Các tác vụ phổ biến để bạn bắt đầu',
    'dashboard.quickActions.addMenuItem': 'Thêm món ăn',
    'dashboard.quickActions.openPOS': 'Mở hệ thống POS',
    'dashboard.quickActions.posSystem': 'Hệ thống POS',
    'dashboard.quickActions.previewPublicMenu': 'Xem trước thực đơn công khai',
    'dashboard.quickActions.previewMenu': 'Xem trước thực đơn',
    'dashboard.quickActions.viewAnalytics': 'Xem phân tích',
    'dashboard.quickActions.manageOrders': 'Quản lý đơn hàng',

    // Hourly Activity
    'dashboard.hourlyActivity.title': 'Hoạt động theo giờ',
    'dashboard.hourlyActivity.description': 'Đơn hàng theo giờ trong ngày',

    // Top Menu Items
    'dashboard.topMenuItems.title': 'Món ăn phổ biến nhất',
    'dashboard.topMenuItems.description': 'Món ăn phổ biến nhất theo đơn hàng',
    'dashboard.topMenuItems.orders': 'đơn hàng',

    // Revenue by Dates
    'dashboard.revenueByDates.title': 'Doanh thu theo ngày',
    'dashboard.revenueByDates.description': 'Doanh thu hàng ngày trong 7 ngày qua',
    'dashboard.revenueByDates.avgPerDay': 'Trung bình mỗi ngày',
    'dashboard.revenueByDates.revenue': 'Doanh thu',
    'dashboard.revenueByDates.orders': 'Đơn hàng',
    'dashboard.revenueByDates.thisWeek': 'Tuần này',
    'dashboard.revenueByDates.bestDay': 'Ngày tốt nhất',
    'dashboard.revenueByDates.totalOrders': 'Tổng đơn hàng',

    // Dashboard Header Actions
    'dashboard.timeRange.today': 'Hôm nay',
    'dashboard.timeRange.yesterday': 'Hôm qua',
    'dashboard.timeRange.thisWeek': 'Tuần này',
    'dashboard.timeRange.lastWeek': 'Tuần trước',
    'dashboard.timeRange.thisMonth': 'Tháng này',
    'dashboard.timeRange.lastMonth': 'Tháng trước',
    'dashboard.actions.customRange': 'Khoảng tùy chỉnh',
    'dashboard.actions.custom': 'Tùy chỉnh',
    'dashboard.actions.exportReport': 'Xuất báo cáo',
    'dashboard.actions.export': 'Xuất',

    // Restaurants Page
    'dashboard.restaurants.loading': 'Đang tải các nhà hàng...',
    'dashboard.restaurants.createTitle': 'Tạo nhà hàng của bạn',
    'dashboard.restaurants.managementTitle': 'Quản lý nhà hàng',
    'dashboard.restaurants.createDescription': 'Hoàn thành thiết lập bằng cách tạo hồ sơ nhà hàng',
    'dashboard.restaurants.managementDescription': 'Quản lý nhiều địa điểm nhà hàng, mỗi địa điểm có thực đơn, bàn và dữ liệu riêng.',
    'dashboard.restaurants.welcomeTitle': 'Chào mừng! Hãy tạo nhà hàng của bạn',
    'dashboard.restaurants.welcomeDescription': 'Chúng tôi sẽ giúp bạn thiết lập hồ sơ nhà hàng và sau đó chọn mẫu thực đơn để bắt đầu nhanh chóng.',
    'dashboard.restaurants.form.name': 'Tên nhà hàng',
    'dashboard.restaurants.form.namePlaceholder': 'Tên nhà hàng của bạn',
    'dashboard.restaurants.form.description': 'Mô tả',
    'dashboard.restaurants.form.descriptionPlaceholder': 'Mô tả ngắn gọn về nhà hàng của bạn',
    'dashboard.restaurants.form.address': 'Địa chỉ',
    'dashboard.restaurants.form.addressPlaceholder': '123 Đường Chính, Thành phố, Tỉnh',
    'dashboard.restaurants.form.phone': 'Số điện thoại',
    'dashboard.restaurants.form.phonePlaceholder': '(555) 123-4567',
    'dashboard.restaurants.form.email': 'Email',
    'dashboard.restaurants.form.emailPlaceholder': 'lienhe@nhahang.com',
    'dashboard.restaurants.form.creating': 'Đang tạo...',
    'dashboard.restaurants.form.createButton': 'Tạo nhà hàng & Tiếp tục',
    'dashboard.restaurants.noRestaurantsTitle': 'Chưa có nhà hàng nào',
    'dashboard.restaurants.noRestaurantsDescription': 'Tạo địa điểm nhà hàng đầu tiên để bắt đầu quản lý thực đơn, bàn và đơn hàng.',
    'dashboard.restaurants.yourRestaurants': 'Nhà hàng của bạn',
    'dashboard.restaurants.selectDescription': 'Chọn một nhà hàng để quản lý dữ liệu của nó',
    'dashboard.restaurants.restaurantSingular': 'nhà hàng',
    'dashboard.restaurants.restaurantsPlural': 'nhà hàng',

    // Menu Builder
    'menuBuilder.header.title': 'Trình tạo thực đơn',
    'menuBuilder.header.description': 'Tạo và quản lý thực đơn nhà hàng với tính năng kéo thả dễ dàng.',
    'menuBuilder.header.previewPublicMenu': 'Xem trước thực đơn công khai',
    'menuBuilder.header.previewMenu': 'Xem trước thực đơn',
    'menuBuilder.header.livePreviewReady': 'Xem trước trực tiếp sẵn sàng',
    'menuBuilder.header.quickTemplates': 'Mẫu nhanh',
    'menuBuilder.header.templates': 'Mẫu',
    'menuBuilder.header.restaurantMenu': 'Thực đơn nhà hàng',
    'menuBuilder.header.general': 'Tổng quát',
    'menuBuilder.header.cafeMenu': 'Thực đơn cà phê',
    'menuBuilder.header.coffeePastries': 'Cà phê & Bánh ngọt',
    'menuBuilder.header.pizzaShop': 'Cửa hàng pizza',
    'menuBuilder.header.pizzaSides': 'Pizza & Món phụ',
    'menuBuilder.header.clearMenu': 'Xóa thực đơn',
    'menuBuilder.header.clear': 'Xóa',
    'menuBuilder.header.scanToView': 'Quét để xem thực đơn',
    'menuBuilder.header.qrDescription': 'Khách hàng có thể quét mã QR này để truy cập ngay thực đơn của bạn',
    'menuBuilder.header.copyUrl': 'Sao chép URL',
    'menuBuilder.header.downloadQr': 'Tải QR',
    'menuBuilder.header.urlCopied': 'Đã sao chép URL thực đơn vào clipboard!',
    'menuBuilder.header.menuUrl': 'URL thực đơn',
    'menuBuilder.tabs.builder': 'Tạo lập',
    'menuBuilder.tabs.options': 'Tùy chọn',
    'menuBuilder.tabs.brand': 'Thương hiệu',

    // Menu Builder - Builder Tab
    'menuBuilder.builder.categoryNamePlaceholder': 'Tên danh mục',
    'menuBuilder.builder.add': 'Thêm',
    'menuBuilder.builder.cancel': 'Hủy',
    'menuBuilder.builder.addCategory': 'Thêm danh mục',
    'menuBuilder.builder.collapseAll': 'Thu gọn tất cả',
    'menuBuilder.builder.collapse': 'Thu gọn',
    'menuBuilder.builder.expandAll': 'Mở rộng tất cả',
    'menuBuilder.builder.expand': 'Mở rộng',
    'menuBuilder.builder.noCategoriesTitle': 'Chưa có danh mục nào',
    'menuBuilder.builder.noCategoriesDescription': 'Bắt đầu bằng cách thêm danh mục đầu tiên để sắp xếp các món ăn',
    'menuBuilder.builder.addFirstCategory': 'Thêm danh mục đầu tiên',
    'menuBuilder.builder.menuItem': 'Món ăn',

    // Menu Builder - Options Tab
    'menuBuilder.options.title': 'Tùy chọn thực đơn',
    'menuBuilder.options.description': 'Quản lý kích cỡ, topping và các tùy chọn khác cho món ăn',
    'menuBuilder.options.addOptionGroup': 'Thêm nhóm tùy chọn',
    'menuBuilder.options.addGroup': 'Thêm nhóm',
    'menuBuilder.options.editOptionGroup': 'Sửa nhóm tùy chọn',
    'menuBuilder.options.createOptionGroup': 'Tạo nhóm tùy chọn',
    'menuBuilder.options.editDescription': 'Cập nhật cài đặt nhóm tùy chọn và món ăn liên kết',
    'menuBuilder.options.createDescription': 'Tạo nhóm tùy chọn mới (ví dụ: Kích cỡ, Topping, Phụ kiện)',
    'menuBuilder.options.groupName': 'Tên nhóm',
    'menuBuilder.options.groupNamePlaceholder': 'ví dụ: Kích cỡ, Topping, Phụ kiện',
    'menuBuilder.options.descriptionOptional': 'Mô tả (Tùy chọn)',
    'menuBuilder.options.descriptionPlaceholder': 'Mô tả nhóm tùy chọn này...',
    'menuBuilder.options.selectionType': 'Kiểu lựa chọn',
    'menuBuilder.options.singleChoice': 'Lựa chọn đơn (Radio)',
    'menuBuilder.options.multipleChoice': 'Lựa chọn nhiều (Checkbox)',
    'menuBuilder.options.required': 'Bắt buộc',
    'menuBuilder.options.minSelections': 'Lựa chọn tối thiểu',
    'menuBuilder.options.maxSelections': 'Lựa chọn tối đa',
    'menuBuilder.options.applyToDishes': 'Áp dụng cho món ăn',
    'menuBuilder.options.selectDishesDescription': 'Chọn những món ăn mà nhóm tùy chọn này sẽ áp dụng',
    'menuBuilder.options.availableForDishes': 'Sẽ áp dụng cho {count} món ăn',
    'menuBuilder.options.cancel': 'Hủy',
    'menuBuilder.options.updateGroup': 'Cập nhật nhóm',
    'menuBuilder.options.createGroup': 'Tạo nhóm',
    'menuBuilder.options.addOption': 'Thêm tùy chọn',
    'menuBuilder.options.addOptionToGroup': 'Thêm tùy chọn mới vào "{groupName}"',
    'menuBuilder.options.optionName': 'Tên tùy chọn',
    'menuBuilder.options.optionNamePlaceholder': 'ví dụ: Lớn, Thêm phô mai, Không hành tây',
    'menuBuilder.options.additionalPrice': 'Giá thêm',
    'menuBuilder.options.defaultOption': 'Tùy chọn mặc định',

    // Menu Builder - Brand Tab
    'menuBuilder.brand.menuPreview': 'Xem trước thực đơn',
    'menuBuilder.brand.menuPreviewDescription': 'Xem thực đơn của bạn như khách hàng thấy',
    'menuBuilder.brand.previewDevice': 'Thiết bị xem trước',
    'menuBuilder.brand.mobile': 'Điện thoại',
    'menuBuilder.brand.tablet': 'Máy tính bảng',
    'menuBuilder.brand.desktop': 'Máy tính',
    'menuBuilder.brand.themeColor': 'Màu chủ đề',
    'menuBuilder.brand.restaurantLogo': 'Logo nhà hàng',
    'menuBuilder.brand.restaurantLogoAlt': 'Logo nhà hàng',
    'menuBuilder.brand.replaceLogo': 'Thay thế logo',
    'menuBuilder.brand.uploadLogo': 'Tải lên logo',
    'menuBuilder.brand.logoFileTypes': 'PNG hoặc JPG, tối đa 2MB',
    'menuBuilder.brand.autoSave': 'Tự động lưu',
    'menuBuilder.brand.autoSaveDescription': 'Tự động lưu thay đổi mỗi 2 giây',
    'menuBuilder.brand.makeMenuPublic': 'Xuất bản thực đơn',
    'menuBuilder.brand.makeMenuPublicDescription': 'Cho phép khách hàng xem thực đơn của bạn',
    'menuBuilder.brand.showPoweredBy': 'Hiển thị "Powered by OishiMenu"',
    'menuBuilder.brand.showPoweredByDescription': 'Hiển thị thương hiệu của chúng tôi trong footer thực đơn',
    'menuBuilder.brand.customize': 'Tùy chỉnh',
    'menuBuilder.brand.share': 'Chia sẻ',
    'menuBuilder.brand.livePreview': 'Xem trước trực tiếp',
    'menuBuilder.brand.menuIsLive': 'Thực đơn của bạn đã xuất bản và khách hàng có thể truy cập',
    'menuBuilder.brand.menuIsPrivate': 'Thực đơn của bạn đang ở chế độ riêng tư',
    'menuBuilder.brand.featured': 'Nổi bật',
    'menuBuilder.brand.unavailable': 'Hết hàng',
    'menuBuilder.brand.contains': 'Chứa',
    'menuBuilder.brand.menuFooterText': 'Quét mã QR để đặt món • Có dịch vụ phục vụ bàn',

    // POS System
    'pos.title': 'Hệ thống bán hàng',
    'pos.description': 'Tạo đơn hàng thủ công cho khách đi bộ hoặc đặt hàng qua điện thoại',
    'pos.accountDisabled': 'Tài khoản bị vô hiệu hóa',
    'pos.accountDisabledMessage': 'Tài khoản của bạn đã bị vô hiệu hóa. Bạn không thể tạo đơn hàng. Vui lòng liên hệ hỗ trợ để được giúp đỡ.',
    'pos.loadingPOS': 'Đang tải hệ thống POS...',
    'pos.menuItems': 'Món ăn',
    'pos.menuItemsDescription': 'Nhấp để thêm món vào đơn hàng',
    'pos.noMenuItemsTitle': 'Không có món ăn nào',
    'pos.noMenuItemsDescription': 'Tạo thực đơn trong Menu Builder để bắt đầu nhận đơn hàng.',
    'pos.goToMenuBuilder': 'Chuyển đến Menu Builder',
    'pos.orderCart': 'Giỏ hàng',
    'pos.items': 'món',
    'pos.reviewOrder': 'Kiểm tra và hoàn thành đơn hàng',
    'pos.tableSelection': 'Chọn bàn',
    'pos.selectTable': 'Chọn bàn',
    'pos.table': 'Bàn',
    'pos.walkIn': 'Đi bộ',
    'pos.customerName': 'Tên khách hàng',
    'pos.enterCustomerName': 'Nhập tên khách hàng',
    'pos.noItemsInCart': 'Không có món nào trong giỏ hàng',
    'pos.paymentMethod': 'Phương thức thanh toán',
    'pos.cash': 'Tiền mặt',
    'pos.card': 'Thẻ',
    'pos.digitalWallet': 'Ví điện tử',
    'pos.subtotal': 'Tạm tính',
    'pos.tax': 'Thuế (8%)',
    'pos.total': 'Tổng cộng',
    'pos.creatingOrder': 'Đang tạo đơn hàng...',
    'pos.orderCompleted': 'Hoàn thành đơn hàng',
    'pos.createOrder': 'Tạo đơn hàng',
    'pos.printReceipt': 'In hóa đơn',
    'pos.newOrder': 'Đơn hàng mới',
    'pos.orderCreatedSuccessfully': 'Tạo đơn hàng thành công!',
    'pos.walkInCustomer': 'Khách đi bộ',
    'pos.orderCreationFailed': 'Tạo đơn hàng thất bại. Vui lòng thử lại.',

    // Orders
    'orders.title': 'Đơn hàng',
    'orders.description': 'Quản lý và theo dõi đơn hàng khách hàng theo thời gian thực.',
    'orders.activeOrders': 'Đơn hàng đang xử lý',
    'orders.active': 'Đang xử lý',
    'orders.allOrders': 'Tất cả đơn hàng',
    'orders.all': 'Tất cả',
    'orders.loadingActiveOrders': 'Đang tải đơn hàng đang xử lý...',
    'orders.kitchenDashboard': 'Bảng điều khiển bếp',
    'orders.kitchenDashboardDescription': 'Đơn hàng đang xử lý cần chú ý',
    'orders.priority.high': 'Ư tiên cao',
    'orders.priority.highShort': 'Cao',
    'orders.priority.medium': 'Ư tiên trung bình',
    'orders.priority.mediumShort': 'TB',
    'orders.priority.low': 'Ư tiên thấp',
    'orders.priority.lowShort': 'Thấp',
    'orders.searchPlaceholder': 'Tìm kiếm theo bàn, khách hàng hoặc mã đơn hàng...',
    'orders.filterByStatus': 'Lọc theo trạng thái',
    'orders.filter.allActive': 'Tất cả đang xử lý',
    'orders.noActiveOrders': 'Không có đơn hàng đang xử lý',
    'orders.allCaughtUp': 'Đã xử lý xong! Đơn hàng mới sẽ xuất hiện ở đây.',
    'orders.status.pending': 'Chờ xử lý',
    'orders.status.preparing': 'Đang chuẩn bị',
    'orders.status.ready': 'Sẵn sàng',
    'orders.status.delivered': 'Đã giao',
    'orders.status.cancelled': 'Đã hủy',
    'orders.time.justNow': 'Vừa xong',
    'orders.time.minutesAgo': '{minutes} phút trước',
    'orders.time.hoursAgo': '{hours} giờ trước',
    'orders.time.daysAgo': '{days} ngày trước',

    // Tables
    'tables.title': 'Bàn ăn',
    'tables.description': 'Quản lý khu vực ngồi và bố trí bàn ăn nhà hàng.',
    'tables.addArea': 'Thêm khu vực',
    'tables.areaNamePlaceholder': 'Tên khu vực (ví dụ: Khu chính, Sân hiên, Quầy bar)',
    'tables.noAreasYet': 'Chưa có khu vực nào',
    'tables.addFirstAreaDescription': 'Bắt đầu bằng cách thêm khu vực ăn uống đầu tiên để sắp xếp bàn ăn nhà hàng',
    'tables.expandAll': 'Mở rộng tất cả',
    'tables.expand': 'Mở rộng',
    'tables.collapseAll': 'Thu gọn tất cả',
    'tables.collapse': 'Thu gọn',
    'tables.tables': 'bàn',
    'tables.orders': 'đơn hàng',
    'tables.status.active': 'Hoạt động',
    'tables.status.closed': 'Đóng cửa',
    'tables.status.maintenance': 'Bảo trì',
    'tables.tableNamePlaceholder': 'Tên bàn',
    'tables.addTable': 'Thêm bàn',
    'tables.add': 'Thêm',
    'tables.noTablesInArea': 'Chưa có bàn nào trong khu vực này',
    'tables.addFirstTable': 'Thêm bàn đầu tiên',
    'tables.dropTablesHere': 'Hoặc kéo thả bàn vào đây để chuyển chúng tới {areaName}',
    'tables.tableNameExists': 'Bàn tên "{tableName}" đã tồn tại trong {areaName}. Vui lòng chọn tên khác.',

    // Common
    'common.cancel': 'Hủy',

    // Settings
    'settings.title': 'Cài đặt',
    'settings.description': 'Quản lý cài đặt nhà hàng, hồ sơ và tùy chọn của bạn.',
    'settings.tabs.profile': 'Hồ sơ',
    'settings.tabs.subscription': 'Gói dịch vụ',
    'settings.tabs.plan': 'Gói',
    'settings.tabs.notifications': 'Thông báo',
    'settings.tabs.notify': 'TB',
    'settings.tabs.security': 'Bảo mật',
    'settings.profile.title': 'Thông tin hồ sơ',
    'settings.profile.description': 'Cập nhật thông tin cá nhân và thông tin liên hệ.',
    'settings.profile.changePhoto': 'Đổi ảnh',
    'settings.profile.change': 'Đổi',
    'settings.profile.photoFormat': 'JPG, PNG tối đa 2MB',
    'settings.profile.firstName': 'Tên',
    'settings.profile.lastName': 'Họ',
    'settings.profile.email': 'Email',
    'settings.profile.phone': 'Số điện thoại',
    'settings.profile.saveChanges': 'Lưu thay đổi',
    'settings.profile.save': 'Lưu',

    // Insights
    'dashboard.insights.welcome': '📊 Chào mừng đến với bảng điều khiển nhà hàng!',
    'dashboard.insights.addMenu': '🍽️ Thêm món ăn để bắt đầu nhận đơn hàng',
    'dashboard.insights.shareQR': '📱 Chia sẻ mã QR với khách hàng',

    // Footer
    'footer.copyright': '© 2024 OishiMenu. Tất cả quyền được bảo lưu.'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
